In [ ]:
# Pandas Method Task

In [ ]:
# Easy Level (1–10)
# Q1
# Load the dataset and display the first 10 records.

In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("C:/Users/NAYAN/Downloads/customer_churn.csv")
df

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [8]:
df.describe()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
count,1000.00000,951.000000,950.000000,1000.000000,950.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,43.81900,55354.417513,651.422837,29.842000,119.301574,182.155000,60.394000,3.129000,0.517000
std,14.99103,32708.500386,68.271995,5.453511,39.619144,104.205824,34.163166,1.410088,0.499961
min,18.00000,7271.860691,444.172796,15.000000,-7.068153,0.000000,1.000000,1.000000,0.000000
25%,31.00000,40959.853770,605.096009,26.000000,93.330104,88.000000,31.000000,2.000000,0.000000
50%,44.00000,51298.846812,650.746768,30.000000,119.585761,184.000000,61.000000,3.000000,1.000000
75%,56.00000,61285.465584,697.845647,33.000000,146.374081,273.250000,89.250000,4.000000,1.000000
max,69.00000,254852.478291,873.517530,49.000000,244.516408,364.000000,119.000000,5.000000,1.000000

In [5]:
dt =pd.DataFrame(df)
dt

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [6]:
# Q1
# Load the dataset and display the first 10 records.
df.head(10)

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
5,25,NaN,526.743383,18,104.602284,286,37,4,Female,South,0
6,38,75307.124526,NaN,40,141.636341,84,96,1,Female,North,0
7,56,63224.596354,738.380887,35,155.046767,181,71,3,Male,West,1
8,36,49880.410380,611.369930,33,93.266192,314,33,4,Male,West,1
9,40,72199.162083,829.073950,24,117.556973,296,31,4,Male,East,0

In [7]:
# Q2
# Display the last 15 customers.
df.tail(15)

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
985,19,55920.072947,652.655648,30,NaN,195,118,1,Female,East,0
986,62,32061.754069,697.833029,22,66.771795,349,22,5,Male,West,0
987,43,56669.040023,635.348033,32,NaN,83,77,2,Male,East,0
988,31,67949.472300,725.108463,22,92.023418,86,80,1,Female,East,1
989,68,40853.256435,815.471075,26,126.467941,306,116,1,Female,West,1
990,24,47989.742500,594.980978,26,124.114343,337,93,1,Male,East,1
991,20,50220.322921,553.326878,41,125.973676,153,6,4,Male,West,0
992,64,38226.525304,671.267302,36,63.557727,227,26,2,Male,North,0
993,40,NaN,700.509375,22,152.126190,263,75,4,Female,West,0
994,63,48185.777771,633.839354,26,129.585101,222,88,1,Male,South,0
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [10]:
# Q3
# Show 7 random customer records.
df.sample(7)

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
601,38,81151.219753,489.267333,34,106.796392,138,11,2,Female,South,0
6,38,75307.124526,NaN,40,141.636341,84,96,1,Female,North,0
716,20,53358.712011,605.095916,35,56.702881,330,10,4,Male,East,0
722,45,50732.901055,583.049454,22,147.566578,282,113,3,Male,West,1
676,27,64726.482305,739.715066,29,133.377541,64,102,4,Female,West,0
195,69,76284.056651,756.492124,28,171.650954,66,80,5,Female,East,0
804,22,22456.919403,704.837336,17,166.393599,144,41,5,Male,North,1

In [12]:
# Q4
# Print complete dataset information and identify:
# • Total columns
# • Data type of each column
# • Missing values

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    1000 non-null   int64
 1   income                 951 non-null    float64
 2   credit_score           950 non-null    float64
 3   transactions_month     1000 non-null   int64
 4   avg_purchase_value     950 non-null    float64
 5   days_since_last_login  1000 non-null   int64
 6   tenure_months          1000 non-null   int64
 7   num_products           1000 non-null   int64
 8   gender                 1000 non-null   object
 9   region                 1000 non-null   object
 10  churn                  1000 non-null   int64
dtypes: float64(3), int64(6), object(2)
memory usage: 86.1+ KB

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
count,1000.00000,951.000000,950.000000,1000.000000,950.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,43.81900,55354.417513,651.422837,29.842000,119.301574,182.155000,60.394000,3.129000,0.517000
std,14.99103,32708.500386,68.271995,5.453511,39.619144,104.205824,34.163166,1.410088,0.499961
min,18.00000,7271.860691,444.172796,15.000000,-7.068153,0.000000,1.000000,1.000000,0.000000
25%,31.00000,40959.853770,605.096009,26.000000,93.330104,88.000000,31.000000,2.000000,0.000000
50%,44.00000,51298.846812,650.746768,30.000000,119.585761,184.000000,61.000000,3.000000,1.000000
75%,56.00000,61285.465584,697.845647,33.000000,146.374081,273.250000,89.250000,4.000000,1.000000
max,69.00000,254852.478291,873.517530,49.000000,244.516408,364.000000,119.000000,5.000000,1.000000

In [13]:
df.select_dtypes(include = float)

           income  credit_score  avg_purchase_value
0             NaN    770.887470           84.828689
1    53051.954538    622.025467          133.943805
2    38654.738821    665.727931          114.993023
3    28666.194356    715.281358          153.875284
4    40301.406736           NaN          115.391031
..            ...           ...                 ...
995  56292.986659    751.728246          149.322171
996  36687.617333    556.297594           44.289513
997  43438.125495    698.504304          132.459634
998  60835.720367    607.589743           72.489390
999  44407.502719    770.356453          104.107070

[1000 rows x 3 columns]

In [16]:
# Q5
# Find missing values in every column.
df.isnull()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False

In [20]:
# Q6
# Display only numerical columns.
df.select_dtypes(include = int)

,age,transactions_month,days_since_last_login,tenure_months,num_products,churn
0,56,29,143,90,1,1
1,69,41,72,96,4,1
2,46,36,155,88,3,1
3,32,29,76,110,2,0
4,60,27,168,99,2,1
...,...,...,...,...,...,...
995,60,26,120,93,4,0
996,64,40,172,3,4,1
997,62,33,3,52,2,0
998,35,49,341,74,3,1
999,55,36,127,60,4,1

In [21]:
df.select_dtypes(include = float)

           income  credit_score  avg_purchase_value
0             NaN    770.887470           84.828689
1    53051.954538    622.025467          133.943805
2    38654.738821    665.727931          114.993023
3    28666.194356    715.281358          153.875284
4    40301.406736           NaN          115.391031
..            ...           ...                 ...
995  56292.986659    751.728246          149.322171
996  36687.617333    556.297594           44.289513
997  43438.125495    698.504304          132.459634
998  60835.720367    607.589743           72.489390
999  44407.502719    770.356453          104.107070

[1000 rows x 3 columns]

In [22]:
# Q7
# Generate the statistical summary of numerical columns.
# 1 ans 
df.describe()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
count,1000.00000,951.000000,950.000000,1000.000000,950.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,43.81900,55354.417513,651.422837,29.842000,119.301574,182.155000,60.394000,3.129000,0.517000
std,14.99103,32708.500386,68.271995,5.453511,39.619144,104.205824,34.163166,1.410088,0.499961
min,18.00000,7271.860691,444.172796,15.000000,-7.068153,0.000000,1.000000,1.000000,0.000000
25%,31.00000,40959.853770,605.096009,26.000000,93.330104,88.000000,31.000000,2.000000,0.000000
50%,44.00000,51298.846812,650.746768,30.000000,119.585761,184.000000,61.000000,3.000000,1.000000
75%,56.00000,61285.465584,697.845647,33.000000,146.374081,273.250000,89.250000,4.000000,1.000000
max,69.00000,254852.478291,873.517530,49.000000,244.516408,364.000000,119.000000,5.000000,1.000000

In [23]:
#2 ans 
df.select_dtypes(include ="number")

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,1
...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,1

In [31]:
# Q8
# Find duplicate rows and print how many exist.
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [64]:
# Q9
# Remove duplicate rows and store the cleaned dataset.
cd = df.drop_duplicates("Age",axis = 1)
cd

TypeError: DataFrame.drop_duplicates() got an unexpected keyword argument 'axis'

In [ ]:
# Q10
# Count how many customers have exited and how many have not exited.

In [39]:
count = df["churn"].value_counts()
print(count)

churn
1    517
0    483
Name: count, dtype: int64

# Medium Level (11–20)
Q11
Rename the following columns:
CustomerId → Customer_ID
CreditScore → Credit_Score
EstimatedSalary → Salary
Exited → Churn

In [45]:
rn = df.rename(columns={"age":"Age_No","avg_purchase_value":"avg_purchase_value_list "})
rn

,Age_No,income,credit_score,transactions_month,avg_purchase_value_list,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [56]:
# Q12
# Add the prefix
# Bank_
# to every column name.
import pandas as pd 
df=df.add_prefix("Bank_")
df

,Bank_ageBank_,Bank_incomeBank_,Bank_credit_scoreBank_,Bank_transactions_monthBank_,Bank_avg_purchase_valueBank_,Bank_days_since_last_loginBank_,Bank_tenure_monthsBank_,Bank_num_productsBank_,Bank_genderBank_,Bank_regionBank_,Bank_churnBank_
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [59]:
#Q13
# Convert the Age column into float datatype.
import pandas as pd 
df

,Bank_ageBank_,Bank_incomeBank_,Bank_credit_scoreBank_,Bank_transactions_monthBank_,Bank_avg_purchase_valueBank_,Bank_days_since_last_loginBank_,Bank_tenure_monthsBank_,Bank_num_productsBank_,Bank_genderBank_,Bank_regionBank_,Bank_churnBank_
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1
...,...,...,...,...,...,...,...,...,...,...,...
995,60,56292.986659,751.728246,26,149.322171,120,93,4,Male,West,0
996,64,36687.617333,556.297594,40,44.289513,172,3,4,Male,South,1
997,62,43438.125495,698.504304,33,132.459634,3,52,2,Male,East,0
998,35,60835.720367,607.589743,49,72.489390,341,74,3,Male,West,1
999,55,44407.502719,770.356453,36,104.107070,127,60,4,Female,South,1

In [61]:
convert = df["Bank_ageBank_"].astype(float)
convert

0      56.0
1      69.0
2      46.0
3      32.0
4      60.0
       ...
995    60.0
996    64.0
997    62.0
998    35.0
999    55.0
Name: Bank_ageBank_, Length: 1000, dtype: float64

In [65]:
# Q14
# Convert the Exited column into string datatype.
convert1 = df["Bank_churnBank_"].astype(str)
convert1

0      1
1      1
2      1
3      0
4      1
      ..
995    0
996    1
997    0
998    1
999    1
Name: Bank_churnBank_, Length: 1000, dtype: object

In [82]:
# Q15
# Suppose the Balance column has missing values.
# Replace them using the mean of the Balance column.
# Fixed syntax error
df["Bank_churnBank_"] = df["Bank_churnBank_"].fillna(df["Bank_churnBank_"].mean())
df["Bank_churnBank_"]

0      1
1      1
2      1
3      0
4      1
      ..
995    0
996    1
997    0
998    1
999    1
Name: Bank_churnBank_, Length: 1000, dtype: int64

In [83]:
# Q16
# Suppose the Age column has missing values.
# Replace them using the median age.

KeyError: 'Bank_Age'

In [84]:
df["Bank_churnBank_"] = df["Bank_churnBank_"].fillna(df["Bank_churnBank_"].median())
df["Bank_churnBank_"]

0      1
1      1
2      1
3      0
4      1
      ..
995    0
996    1
997    0
998    1
999    1
Name: Bank_churnBank_, Length: 1000, dtype: int64

In [ ]:
# 17 Display only the first five rows after renaming the columns.

In [86]:
nt= df.co()  df.head(5)
nt

TypeError: 'Series' object is not callable