# pandas methods  60 % data set operation  pd-python identifier 
any data in table form we use pandas 
# dataFrame - used to convert dict /json / 
function required parameter methods not need parameter 
# file name with file extension file path need to acces file in project system 
# mention the file file_csv ,file_html,
# file extension excell - xlxs , 
# lot or files are not allowed the available in unicode format / , \ ,\\

In [1]:
import pandas as pd

In [5]:
dicts = { "Name": ["sumit","Rajesh","rakhi"],
          "Age": [10,12,13],
          "Gender":["Male","Male","Female"]}
dicts

{'Name': ['sumit', 'Rajesh', 'rakhi'],
 'Age': [10, 12, 13],
 'Gender': ['Male', 'Male', 'Female']}

In [11]:
df  = pd.DataFrame(dicts)
df

     Name  Age  Gender
0   sumit   10    Male
1  Rajesh   12    Male
2   rakhi   13  Female

# method 2: load_csv : load the dataset

In [19]:
pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [7]:
import pandas as pd
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")   
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [22]:
df1 = pd.read_csv("C:/Users/NAYAN/Downloads/dataset.csv")   
df1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:

df1 = pd.read_csv("C:\Users\NAYAN\Downloads\dataset.csv",encoding =  )   
df1

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3073189711.py, line 1)

In [27]:
# method 3 : head () display top five rows 
df .head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [28]:
# method 3 : head () display top five rows 
df .head(7)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1

In [29]:
# method 4:tail () display last five 
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [30]:
# method:sample () display random rows are there  
df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2,1

In [36]:
# # method 6: shape : display  rows and colums in no   # without bracket ()
df.shape

(303, 14)

In [37]:
# method 7:info ()  give whole info for the data set 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [38]:
# method 8 : columns : check the columns name of the data set 
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [39]:
# method 9 : dtypes : check the all colums of data type 
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [41]:
# method 10 : isnull () check the missing value 
df.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [42]:

# method 10 : isnull () check the missing value  of every colum by using sum 
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [43]:
# method 11 : isna() check the missing value same like isnull() both are work for to check the missing value 
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [46]:
# method 12 : select_dtype : select the specific single column from whole data set 
Target = df['target']
Target

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [47]:
# method 13 : select_dtype : select the multiple  column 
df[["age","sex","cp"]]

     age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [54]:
# method 14 : select_dtype : select the specific type of we can select any obj from whole data set 
int_columns = df.select_dtypes(include=["int"]).columns
int_columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [56]:
# method 15 : describe  : show the stastical summary of data set  data set
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [72]:
# method 16 : drop () droup the columns from the data set  # axis = 1 
# true ka mtlab  1 , axis = 1  temperory droup the columns ,
# inplace = True for permenant delete the 

df.drop("exang",axis = 1,inplace = True )

KeyError: "['exang'] not found in axis"

In [70]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [75]:
# method 17 : duplicated() : check the duplicated rows 
df.duplicated()
# count

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [81]:
df.duplicated().sum()

_IncompleteInputError: incomplete input (1336542280.py, line 1)

In [83]:
# method 18 : drop_duplicates () droup the duplicates rows in data set 
df.drop_duplicates().sum()

age         16435.0
sex           206.0
cp            291.0
trestbps    39744.0
chol        74443.0
fbs            45.0
restecg       159.0
thalach     45170.0
oldpeak       315.0
slope         422.0
ca            217.0
thal          699.0
target        164.0
dtype: float64

In [86]:
df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [85]:
# method 19 : value_count(): check the value count in columns including missing values and spaces 
df["target"].value_counts(dropna = True)

target
1    165
0    138
Name: count, dtype: int64

In [10]:
# Renaming & type conversion 

# method 19 : rename () : change the column name
df.rename(columns = {"target":"Result","sex":"Gender"},inplace = True )
df

,age,Gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
df.columns = [col.title() for col in  df.columns]

In [12]:
df.columns

Index(['Age', 'Gender', 'Cp', 'Trestbps', 'Chol', 'Fbs', 'Restecg', 'Thalach',
       'Exang', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Result'],
      dtype='object')

In [15]:
df.add_prefix("col_")   # add name at starting of title

,col_Age,col_Gender,col_Cp,col_Trestbps,col_Chol,col_Fbs,col_Restecg,col_Thalach,col_Exang,col_Oldpeak,col_Slope,col_Ca,col_Thal,col_Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [16]:
df.add_suffix("_col")  # add name at ending  of titple

,Age_col,Gender_col,Cp_col,Trestbps_col,Chol_col,Fbs_col,Restecg_col,Thalach_col,Exang_col,Oldpeak_col,Slope_col,Ca_col,Thal_col,Result_col
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
# method 21 : astype() change the type of column value   ex - int - flot , col-col column in to interger

In [21]:
df['col_Oldpeak'] = df['col_Oldpeak'].astype("int")
select_float = df.select_dtypes(include = ["int"]).columns

for col in select_int:
    df[col]

KeyError: 'col_Oldpeak'

In [ ]:
#

In [ ]:
dicts = {"Age" : [10,12,13,14,15,np]}

In [ ]:
df = pd.DataFrame(dicts)
df

In [ ]:
# check the missing values 
df.isnull().sum()

In [ ]:
df['Age'].value_counts(droup = False)

# method 22 fillna () fill the missing value

In [ ]:
# df.fillna  fill all missing values in table

In [24]:
df["Age"].fillna('unknow',inplace = True)
df

C:\Users\NAYAN\AppData\Local\Temp\ipykernel_22760\554314043.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna('unknow',inplace = True)

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
# outlier is there median 
# not outlier then mean 
# mean alwasy calculate the numeric value 
#  mode

In [26]:
# 1 mean 
age_mean = df['Age'].mean()
age_mean

np.float64(54.366336633663366)

In [27]:
# 1 mean 
age_mean = int(df['Age'].mean())
age_mean

54

In [28]:
# fill the missing value using mean of age 
df['Age'] = df["Age"].fillna(age_mean)

In [29]:
df['Age']= df['Age'].astype("int")
df["Age"]

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: Age, Length: 303, dtype: int64

# mediam method 2 # fill the missing value using mean of age

In [30]:
# mediam method 2 # fill the missing value using mean of age
age_median = df['Age'].median()
age_median

55.0

In [31]:
age_median = int(df['Age'].median())
age_median

55

In [32]:
df['Age'] = df["Age"].fillna(age_median)

In [33]:
df['Age']= df['Age'].astype("int")
df["Age"]

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: Age, Length: 303, dtype: int64

In [4]:
import pandas as pd
# method 24 : bfill :

In [6]:
df["age"].fillna(method = "bfill", inplace = True )

NameError: name 'df' is not defined

In [ ]:
# method 25 : dropna () drop the missing values from the data set 
df.dropna()

In [ ]:
# method 26 : notnull () which value are not null from the data set 
df.dropna()

In [8]:
import pandas as pd
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")   
df.notnull().sum()

age         303
sex         303
cp          303
trestbps    303
chol        303
fbs         303
restecg     303
thalach     303
exang       303
oldpeak     303
slope       303
ca          303
thal        303
target      303
dtype: int64

In [9]:
import pandas as pd
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")   
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
import pandas as pd
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")   
df.shape

(303, 14)

In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\dataset.csv")   
df.notnull().sum()

In [12]:
# method 27 : replace () for the value  with another value   # try examples more and more 
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [13]:
# method 27 : sorting  () it sort the columns value 
df.sort_values("age")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0

In [14]:
# method 27 : sorting  () it sort the columns value 
df.sort_values("age",ascending = False)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
227,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1

In [15]:
# method 27 : sorting  () it sort the columns value 
df.sort_values("age",ascending = True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0

In [17]:
# method 27 : sort_index () it sort the index 
df.sort_index(ascending = False)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1

In [ ]:
# grouping & agrregation technique 
# mean 
#  max 
# median '
#

In [19]:
df.groupby("sex")["age"].mean()

sex
0    55.677083
1    53.758454
Name: age, dtype: float64

In [20]:
df.groupby("sex")["age"].sum()

sex
0     5345
1    11128
Name: age, dtype: int64

In [21]:
df.groupby("sex")["age"].median()

sex
0    57.0
1    54.0
Name: age, dtype: float64