In [ ]:
# Pandas Challenges (Based on Your Notebook)
# Challenge 1 – Complete Data Cleaning
# Your manager gives you a messy dataset.

In [3]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [5]:
df.isnull()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1015,False,False,False,False,False,False,False,False,False,False,False
1016,False,False,False,False,False,False,False,False,True,False,False
1017,False,False,False,False,False,False,False,False,False,False,False
1018,False,False,True,False,False,False,False,False,False,False,False
1019,False,False,False,False,False,True,False,False,False,True,False

In [6]:
df.drop_duplicates()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [9]:
df["Age"].median()

44.0

In [14]:
df["Balance"].mean()

np.float64(97523.53566563467)

In [18]:
df.rename(columns={"Target":"CustomerStatus"})

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [19]:
df.rename(columns = {"AnnualIncome":"Income"})

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [20]:
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn

# Challenge 2 – Banking Report
# The bank wants a numeric report.
# Tasks
# 1)Select only numeric columns.
# 2)Display summary statistics.
# • Convert Age and CreditScore to float.
# • Display information again.

In [24]:
df.select_dtypes(include = "number")   # Select only numeric columns.

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
0,10001,58.0,49184.0,2139,581,NaN,2
1,10002,65.0,162964.0,6197,732,6356.54,1
2,10003,56.0,26956.0,37281,503,143203.92,8
3,10004,55.0,92926.0,925,463,139627.88,5
4,10005,66.0,108236.0,7198,394,75985.46,5
...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2
1016,10753,25.0,54490.0,13794,303,124512.07,4
1017,10810,49.0,82062.0,47170,813,53850.09,8
1018,10267,38.0,NaN,10424,722,138100.05,6
1019,10059,62.0,97504.0,36833,430,NaN,10

## 2)Display summary statistics. ##

In [25]:
df.describe()   # Display summary statistics.

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

 ## 3)Convert Age and CreditScore to float ##

In [30]:
df["Age"].astype(float)

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [31]:
df["CreditScore"].astype(float)

0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64

# # Display information again.##

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

## Challenge 3 – Duplicate Investigation ##
# Find duplicate customers.
# Then
#  Count duplicate rows.
# Remove duplicates.
# Print information before and after removing duplicates.
# Show the last 20 rows.

In [46]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [15]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")
df.info
print(df.duplicated().sum())
df.info()
df.tail(20)

20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1000,10643,41.0,125012.0,18825,761,35977.85,2,Germany,Other,Retail,Stay
1001,10763,56.0,102965.0,17517,838,115028.54,9,UK,NaN,SME,Stay
1002,10910,66.0,118506.0,6296,306,81892.13,4,Canada,Male,SME,Churn
1003,10200,19.0,115052.0,20741,484,190233.86,5,Canada,Male,Retail,Churn
1004,10587,29.0,NaN,40255,383,168358.60,2,Germany,Male,Corporate,Churn
1005,10798,22.0,176830.0,7626,688,65481.65,10,France,Male,Retail,Stay
1006,10653,32.0,NaN,21266,598,142086.70,9,France,Female,Corporate,Stay
1007,10756,53.0,74430.0,3705,489,29651.23,10,UK,Male,Retail,Churn
1008,10417,70.0,40417.0,37956,681,23880.19,10,India,Male,Retail,Stay
1009,10499,34.0,166546.0,12497,643,130886.93,3,UK,Male,SME,Stay
1010,10515,62.0,199762.0,41808,309,60223.29,10,India,Other,SME,Churn
1011,10457,44.0,63604.0,27633,804,176354.13,5,Germany,Female,Retail,Stay
1012,10882,61.0,115417.0,3879,413,76591.00,7,NaN,Male,Corporate,Churn
1013,10531,64.0,85162.0,32083,654,132742.13,10,Canada,Male,SME,Stay
1014,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [ ]:

# ✅ Challenge 4 – HR Department

In [42]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")
df = df.rename(columns ={" CustomerID ":"Employee_ID","Age":"Employee_Age","Gender":"Employee_Gender","Annual_Income":"Salary","Target":"Promotion_Status"})
df = df.add_prefix("HR_")
df.sample(10)

,HR_Employee_ID,HR_Employee_Age,HR_AnnualIncome,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_Employee_Gender,HR_Segment,HR_Promotion_Status
933,10934,24.0,67408.0,23753,688,84818.37,8,NaN,Female,NaN,Stay
461,10462,64.0,161590.0,17884,588,59480.13,1,India,Female,SME,Churn
371,10372,46.0,182374.0,4013,667,NaN,7,USA,Male,Corporate,Stay
27,10028,24.0,192748.0,28749,662,84715.72,7,France,Male,SME,Stay
100,10101,70.0,37129.0,26760,803,NaN,10,France,Male,Retail,Churn
845,10846,22.0,NaN,42666,615,99936.83,7,India,Male,Corporate,Stay
717,10718,27.0,42495.0,7864,355,48609.66,9,USA,Female,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
816,10817,60.0,96481.0,48824,327,57363.13,1,USA,Other,Retail,Churn
311,10312,61.0,178589.0,40013,340,174724.09,3,Germany,Other,SME,Churn

# Challenge 5 – Finance Cleaning
# Finance department reports missing values.
 #   Tasks
# Fill
# AnnualIncome → Median
# Balance → Mean
# Age → Median
# Then
# Generate descriptive statistics.

In [56]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] =df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())
print(df.describe())

        CustomerID           Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  1020.000000    1020.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112498.242157  25232.615686   602.659804
std      288.022115    15.136428   50925.015723  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   69223.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    57.000000  155570.750000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1020.000000  1020.000000
mean    97523.535666     5.261765
std     54382.357541     3.185330
min       547.600000     0.000000
25%     52145.757500     2.000000
50%     97523.535666     5.000000
75%    142086.700000     8.000000
max    199885.880000    10.000000

In [53]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())

df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df["Age"] = df["Age"].fillna(df["Age"].median())

print(df.describe())

        CustomerID           Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  1020.000000    1020.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112498.242157  25232.615686   602.659804
std      288.022115    15.136428   50925.015723  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   69223.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    57.000000  155570.750000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1020.000000  1020.000000
mean    97523.535666     5.261765
std     54382.357541     3.185330
min       547.600000     0.000000
25%     52145.757500     2.000000
50%     97523.535666     5.000000
75%    142086.700000     8.000000
max    199885.880000    10.000000

In [ ]:
# Challenge 6 – Data Type Audit

In [ ]:
#Challenge 6 – Data Type Audit
#The company says
#Age and AnnualIncome are stored incorrectly.
#Tasks
#Convert
#Age → int
#AnnualIncome → float
#Balance → float
#Target → string
#Print information.

In [57]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

df["Age"] = df["Age"].astype(int)

df["AnnualIncome"] = df["AnnualIncome"].astype(float)

df["Balance"] = df["Balance"].astype(float)

df["Target"] = df["Target"].astype(str)

df.info()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
# Challenge 7 – Customer Analytics

In [58]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

new_df = df.drop(columns=["Segment","Geography"])

new_df = new_df.drop_duplicates()

print(new_df.head(10))

new_df.info()

print(new_df.describe())

    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5
5         10006  69.0       31390.0     48323          770  107245.62       6
6         10007  58.0      182141.0     24200          891   38457.72       1
7         10008  67.0       95861.0      5729          538  173296.73       6
8         10009  41.0       62638.0     24760          663   41901.41       4
9         10010  22.0      179680.0     42113          475  106827.98       3

   Gender Target
0    Male   Stay
1    Male  Churn
2    Male   Stay
3    Male  Churn
4   Other  Churn
5   Other   Stay
6   Other  Churn
7  Female   Stay
8   Other   Stay
9  Female  Churn
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(3), int64(4), object(2)
memory usage: 78.1+ KB
        CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1000.000000  950.000000     950.000000   1000.000000  1000.000000
mean   10500.500000   44.212632  112458.303158  25285.558000   603.088000
std      288.819436   15.524244   52409.868404  14211.735656   176.605486
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10250.750000   30.000000   65922.500000  13213.000000   441.000000
50%    10500.500000   44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000   58.000000  157973.000000  37960.250000   758.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     950.000000  1000.000000
mean    97557.565779     5.241000
std     55845.536430     3.179155
min       547.600000     0.000000
25%     50003.880000     2.000000
50%     95174.625000     5.000000
75%    144198.130000     8.000000
max    199885.880000    10.000000

In [ ]:
# challenge 8 – ML Dataset Preparation

In [60]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

df = df.drop_duplicates()

df = df.drop(columns=[" CustomerID ","Segment"])

df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df = df.rename(columns={"Target":"Output"})

print(df.head())

df.info()

print(df.describe())

print(df["Output"].value_counts())

    Age  AnnualIncome  Spending  CreditScore        Balance  Tenure Geography  \
0  58.0       49184.0      2139          581   97557.565779       2    France
1  65.0      162964.0      6197          732    6356.540000       1       USA
2  56.0       26956.0     37281          503  143203.920000       8    Canada
3  55.0       92926.0       925          463  139627.880000       5       NaN
4  66.0      108236.0      7198          394   75985.460000       5        UK

  Gender Output
0   Male   Stay
1   Male  Churn
2   Male   Stay
3   Male  Churn
4  Other  Churn
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           1000 non-null   float64
 1   AnnualIncome  1000 non-null   float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       1000 non-null   float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    object
 7   Gender        950 non-null    object
 8   Output        1000 non-null   object
dtypes: float64(3), int64(3), object(3)
memory usage: 78.1+ KB
               Age   AnnualIncome      Spending  CreditScore        Balance  \
count  1000.000000    1000.000000   1000.000000  1000.000000    1000.000000
mean     44.202000  112452.763000  25285.558000   603.088000   97557.565779
std      15.130834   51081.480963  14211.735656   176.605486   54430.062006
min      18.000000   20227.000000    537.000000   300.000000     547.600000
25%      31.000000   68437.250000  13213.000000   441.000000   52074.240000
50%      44.000000  112347.500000  24901.000000   606.500000   97557.565779
75%      57.000000  155570.750000  37960.250000   758.250000  142297.910000
max      70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1000.000000
mean      5.241000
std       3.179155
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000
Output
Churn    506
Stay     494
Name: count, dtype: int64

In [ ]:
# Challenge 9 – Column Transformation

In [61]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

df["NetWorth"] = df["Balance"] + df["AnnualIncome"]

df["AgeAfterRetirement"] = df["Age"] + 20

df["DoubleCreditScore"] = df["CreditScore"] * 2

df["IncomePerMonth"] = df["AnnualIncome"] / 12

print(df.head(15))

     CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139          581        NaN
1          10002  65.0      162964.0      6197          732    6356.54
2          10003  56.0       26956.0     37281          503  143203.92
3          10004  55.0       92926.0       925          463  139627.88
4          10005  66.0      108236.0      7198          394   75985.46
5          10006  69.0       31390.0     48323          770  107245.62
6          10007  58.0      182141.0     24200          891   38457.72
7          10008  67.0       95861.0      5729          538  173296.73
8          10009  41.0       62638.0     24760          663   41901.41
9          10010  22.0      179680.0     42113          475  106827.98
10         10011   NaN      187772.0     45599          870   43923.03
11         10012  69.0      102694.0     26790          574   13237.72
12         10013  59.0      150870.0     26428          769   28574.32
13         10014  52.0       88876.0     49456          898   85686.77
14         10015  26.0      153569.0     32843          393  151156.43

    Tenure Geography  Gender    Segment Target   NetWorth  AgeAfterRetirement  \
0        2    France    Male        SME   Stay        NaN                78.0
1        1       USA    Male        SME  Churn  169320.54                85.0
2        8    Canada    Male  Corporate   Stay  170159.92                76.0
3        5       NaN    Male     Retail  Churn  232553.88                75.0
4        5        UK   Other  Corporate  Churn  184221.46                86.0
5        6     India   Other  Corporate   Stay  138635.62                89.0
6        1     India   Other     Retail  Churn  220598.72                78.0
7        6        UK  Female        SME   Stay  269157.73                87.0
8        4    France   Other        SME   Stay  104539.41                61.0
9        3       USA  Female  Corporate  Churn  286507.98                42.0
10       5     India     NaN     Retail   Stay  231695.03                 NaN
11       9    France  Female     Retail  Churn  115931.72                89.0
12       2       USA   Other        SME   Stay  179444.32                79.0
13       9    Canada  Female     Retail   Stay  174562.77                72.0
14       1       USA   Other     Retail  Churn  304725.43                46.0

    DoubleCreditScore  IncomePerMonth
0                1162     4098.666667
1                1464    13580.333333
2                1006     2246.333333
3                 926     7743.833333
4                 788     9019.666667
5                1540     2615.833333
6                1782    15178.416667
7                1076     7988.416667
8                1326     5219.833333
9                 950    14973.333333
10               1740    15647.666667
11               1148     8557.833333
12               1538    12572.500000
13               1796     7406.333333
14                786    12797.416667

In [ ]:
# Challenge 10 – Company Report

In [62]:
import pandas as pd

df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\Task_dataset.csv")

print(df.head())

print(df.tail())

print(df.sample(10))

df.info()

print(df.describe())

df = df.rename(columns={"Target":"Customer_Status"})

    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target
0    France   Male        SME   Stay
1       USA   Male        SME  Churn
2    Canada   Male  Corporate   Stay
3       NaN   Male     Retail  Churn
4        UK  Other  Corporate  Churn
       CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
1015         10450  43.0      173620.0      7121          644   60353.03
1016         10753  25.0       54490.0     13794          303  124512.07
1017         10810  49.0       82062.0     47170          813   53850.09
1018         10267  38.0           NaN     10424          722  138100.05
1019         10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn
      CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  \
670         10671  49.0       76934.0     22907          730   62315.34
657         10658  65.0       94494.0     29542          429   26255.42
432         10433  18.0       36166.0     15067          433   39626.61
269         10270  61.0      198453.0     42659          570  122015.32
133         10134  57.0      120281.0     41113          546   99533.45
783         10784  31.0      162220.0     23458          862   63696.98
618         10619  61.0       33645.0     11034          698  192914.05
405         10406  43.0       41607.0     42478          849  107531.07
505         10506  45.0      145147.0     25621          304    7545.06
338         10339  27.0      122137.0     21253          669   21310.18

     Tenure Geography  Gender    Segment Target
670       7        UK  Female        SME   Stay
657       2     India    Male        SME  Churn
432       6        UK   Other        SME  Churn
269       3       USA  Female        SME   Stay
133       9       USA    Male  Corporate   Stay
783       2    France  Female        SME   Stay
618       0     India    Male  Corporate  Churn
405       2        UK    Male  Corporate   Stay
505       3    France  Female     Retail  Churn
338       0        UK  Female  Corporate  Churn
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    CustomerID   1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
        CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000